Ported generating namespaces for existing scripts to C#
mohamedelzayat-fit/unity-editor-addons pull request #2
Opened 2022-03-22 13:39 UTC by AdivonSlav

I made the necessary changes and ported over the logic I had in my C++ function to a C# class  that hopefully isn't too bad of a solution. It will still probably break in some way if keywords are used inside block comments, but with my limited testing it proved to be adequate enough for simple existing scripts in a project to get their namespaces.

2022-03-24 14:46 UTC, mohamedelzayat-fit requested changes
Thanks a ton for the contribution. Kindly address these minor comments and we can do a merge afterwards :)

2022-03-24 14:46 UTC, mohamedelzayat-fit commented on Editor/NamespaceResolver.cs
> +
Unnecessary space

2022-03-24 14:46 UTC, mohamedelzayat-fit commented on Editor/NamespaceResolver.cs
> +        string[] scripts = Directory.GetFiles(Application.dataPath, "*.cs",SearchOption.AllDirectories);
Search inside the scripts folder only, because we don't want to touch other plugins that probably might be under the Assets folder.

Add space after comma in SearchOptions for better readability

2022-03-24 14:46 UTC, mohamedelzayat-fit commented on Editor/ScriptParser.cs
> +        public static void ParseScript(string filePath, string genNamespace)
Rename method to insert namespace

2022-03-24 14:46 UTC, mohamedelzayat-fit commented on Editor/ScriptParser.cs
> +            }
Separate this into it's own method (CheckNamespace)

2022-03-24 14:46 UTC, mohamedelzayat-fit commented on Editor/ScriptParser.cs
> +namespace FITEditorAddons.ScriptParser
FITEditorAddons.Editor

2022-03-24 14:46 UTC, mohamedelzayat-fit commented on Editor/NamespaceResolver.cs
> +            var generatedNamespace = "";
Follow the naming conventions in the script for consistency sake

2022-03-25 17:52 UTC, AdivonSlav commented
I made the necessary changes according to the comments. Last commit just removed the files from the Rider IDE that I accidentally included with the other commit.

2022-04-01 08:07 UTC, merged